# config.yaml

# General settings
general:
  address: tcp://127.0.0.1:5555
  num_threads: 100

  # num_messages: total number of messages that will be sent by the client
  num_messages: 1000

  # message_size: size of the message in bytes that will be sent by the client (random ascii, avoid caching)
  message_size: 1024
  stats_filepath: "../server_stats"

  # use_json: if true, the stats will be saved in json format, otherwise in csv format
  use_json: false
  save_interval_seconds: 10

  use_msg_per_minute: true

  # msg_per_minute: number of messages that should send in a minute (with use_msg_per_minute = true)
  msg_per_minute: 1000

# Client settings
client:
  sleep_starting_time: 1000

# Server settings
server:
  sleep_starting_time: 3000
