# config.yaml

# General settings
general:
  protocol: "udp"
  main_address: 127.0.0.1:5555
  responder_address: 127.0.0.1:5556
  num_threads: 2

  # num_messages: total number of messages that will be sent by the client
  num_messages: 5000

  # message_size: size of the message in bytes that will be sent by the client (random ascii, avoid caching)
  message_size: 1024
  stats_folder_path: "../stats"

  # use_json: if true, the stats will be saved in json format, otherwise in csv format
  use_json: false
  save_interval_seconds: 20

  use_msg_per_minute: true

  # msg_per_minute: number of messages that should send in a minute (with use_msg_per_minute = true)
  msg_per_minute: 1000

  # signal_msg_timeout: timeout in milliseconds for the signal message (used to check if the server and client are alive)
  signal_msg_timeout: 500


# Client settings
client:
  sleep_starting_time: 1000

# Server settings
server:
  sleep_starting_time: 3000
